[build]
  publish = "dist/protfolio-template-v1/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # European optimization environment variables
  EUROPEAN_OPTIMIZATION = "true"
  GDPR_COMPLIANCE = "true"
  CDN_ENABLED = "true"

# Performance optimizations
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # European GDPR compliance headers
    X-GDPR-Compliance = "true"
    X-Data-Protection = "GDPR"
    # European performance headers
    X-European-Optimization = "true"
    X-CDN-Region = "eu-west-1"

# Static assets with long-term caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"

# CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"

# HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Encoding = "gzip"

# Image files
[[headers]]
  for = "/*.{jpg,jpeg,png,webp,svg}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font files
[[headers]]
  for = "/*.{woff,woff2,ttf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SEO
[[redirects]]
  from = "/hire"
  to = "/hire/"
  status = 301

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# European CDN redirects for better performance
[[redirects]]
  from = "/cdn-eu/*"
  to = "https://cdn-eu-west-1.sachindilshan.netlify.app/:splat"
  status = 301
  force = true

# European language-specific redirects
[[redirects]]
  from = "/de/*"
  to = "/:splat?lang=de"
  status = 301

[[redirects]]
  from = "/fr/*"
  to = "/:splat?lang=fr"
  status = 301

[[redirects]]
  from = "/es/*"
  to = "/:splat?lang=es"
  status = 301

[[redirects]]
  from = "/pt/*"
  to = "/:splat?lang=pt"
  status = 301

[[redirects]]
  from = "/sv/*"
  to = "/:splat?lang=sv"
  status = 301
